/**
 * Created by sunxin on 2016/12/26.
 */
module.exports={
    "Content-Type":[
        "multipart/form-data",
        "application/x-www-form-urlencoded",
        "text/xml",
        "image/gif",
        "text/html",
        "image/jpeg",
        "text/plain",
        "image/png",
        "application/json",
        "application/xml",
        "application/javascript"
    ],
    "Accept":[
        "application/json",
        "application/javascript",
        "text/plain",
        "text/html"
    ],
    "Accept-Encoding":[
        "compress, gzip",
    ],
    "Accept-Charset":[],
    "Accept-Language":[],
    "Accept-Ranges":[],
    "Authorization":[],
    "Cache-Control":[],
    "Connection":[],
    "Cookie":[]
}